# Generated by Django 4.2.3 on 2023-07-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='status',
            field=models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], default='Iniciante', max_length=255),
        ),
    ]
